---
- hosts: all
  tasks:
  - name: Add vagrant folder to fstab
    become: true
    mount:
      path: /vagrant
      src: vagrant
      fstype: vboxsf
      state: present

  - name: Update All Packages
    become: true
    pacman:
      update_cache: yes
      upgrade: yes

  - name: Install Devtools
    action: pacman pkg={{item}} state=latest
    become: true
    with_items: "{{ packages  }}"

  - name: Set default shell
    become: true
    user:
      name: vagrant
      shell: /usr/bin/zsh

  - name: Download custom configs
    git:
      repo: "{{ dotfile_repo  }}"
      dest: /home/vagrant/.etc

  - name: Link custom configs
    script: ~/.etc/link.sh/link.sh -u ~/.etc/.link.conf -wf

  - name: Download Node Version Manager (NVM)
    git:
      repo: https://github.com/creationix/nvm.git
      dest: ~/.nvm
      force: yes
      version: v0.33.11
    when: install_nvm

  - name: Download TFenv
    git:
      repo: https://github.com/kamatama41/tfenv.git
      dest: ~/.tfenv
      force: yes
    when: install_tfenv

  - name: Download PKenv
    git:
      repo: https://github.com/iamhsa/pkenv.git
      dest: ~/.pkenv
      force: yes
    when: install_pkenv

  - name: Add TFEnv to PATH
    copy:
      content: PATH="$PATH:$HOME/.tfenv/bin"
      dest: ~/.etc/zsh/zsh-os-conf/local-post/50-tfenv.zsh
    when: install_tfenv

  - name: Add PKEnv to PATH
    copy:
      content: PATH="$PATH:$HOME/.pkenv/bin"
      dest: ~/.etc/zsh/zsh-os-conf/local-post/50-pkenv.zsh
    when: install_pkenv
