---
- hosts: all
  tasks:
  - name: Add vagrant folder to fstab
    become: true
    mount:
      path: /vagrant
      src: vagrant
      fstype: vboxsf
      state: present

  - name: Update All Packages
    become: true
    apt:
      update_cache: yes
      upgrade: dist

  - name: Install Devtools
    action: apt pkg={{item}} state=installed
    become: true
    with_items:
      - git
      - vim
      - tmux
      - docker.io
      - zsh

  - name: Set default shell
    become: true
    user:
      name: vagrant
      shell: /usr/bin/zsh

  - name: Install oh-my-zsh
    git:
      repo: https://github.com/robbyrussell/oh-my-zsh.git
      dest: /home/vagrant/.oh-my-zsh
      force: yes

  - name: Create themes directory
    file:
      path: "/home/vagrant/.oh-my-zsh/custom/themes"
      state: directory

  - name: Download custom configs
    git:
      repo: https://github.com/Shane4STER/etc.git
      dest: /home/vagrant/.etc
      force: yes

  - name: Link custom configs
    script: /home/vagrant/.etc/link.sh/link.sh -u /home/vagrant/.etc/.link.conf -wf

  - name: Download Bullettrain zsh theme
    get_url: url=http://raw.github.com/caiogondim/bullet-train-oh-my-zsh-theme/master/bullet-train.zsh-theme dest=/home/vagrant/.oh-my-zsh/custom/themes/bullet-train.zsh-theme

  - name: Download Node Version Manager (NVM)
    git:
      repo: https://github.com/creationix/nvm.git
      dest: /home/vagrant/.nvm
      force: yes
      version: v0.33.8


  - name: Remove unneeded dependancies
    become: true
    apt:
      autoremove: yes

  - name: Cleanup
    become: true
    apt:
      autoclean: yes
